from enum import Enum

class AssetStatus(str, Enum):
    ACTIVE = "ACTIVE"
    LOCKED_IN_TRANSFER = "LOCKED_IN_TRANSFER"
    MUTATION_PENDING = "MUTATION_PENDING"
    FROZEN_BY_COURT = "FROZEN_BY_COURT"
    SUBDIVIDED = "SUBDIVIDED"
    MERGED = "MERGED"
    RETIRED = "RETIRED"

class RightType(str, Enum):
    FREEHOLD_OWNERSHIP = "FREEHOLD_OWNERSHIP"
    POSSESSION = "POSSESSION"
    LEASEHOLD = "LEASEHOLD"
    GOVERNMENT_GRANT = "GOVERNMENT_GRANT"
    MORTGAGE_LIEN = "MORTGAGE_LIEN"
    EASEMENT = "EASEMENT"
    DEVELOPMENT_RIGHT = "DEVELOPMENT_RIGHT"

class EncumbranceType(str, Enum):
    BANK_MORTGAGE = "BANK_MORTGAGE"
    REVENUE_TAX_LIEN = "REVENUE_TAX_LIEN"
    ACQUISITION_NOTICE = "ACQUISITION_NOTICE"
    COURT_ATTACHMENT = "COURT_ATTACHMENT"
    ENVIRONMENTAL_RESTRICTION = "ENVIRONMENTAL_RESTRICTION"

class DisputeStatus(str, Enum):
    FILED = "FILED"
    UNDER_HEARING = "UNDER_HEARING"
    INJUNCTION_ISSUED = "INJUNCTION_ISSUED"
    DISMISSED = "DISMISSED"
    RESOLVED = "RESOLVED"

class DisputeType(str, Enum):
    BOUNDARY_ENCROACHMENT = "BOUNDARY_ENCROACHMENT"
    TITLE_OWNERSHIP = "TITLE_OWNERSHIP"
    SUCCESSION_INHERITANCE = "SUCCESSION_INHERITANCE"
    EASEMENT_RIGHT_OF_WAY = "EASEMENT_RIGHT_OF_WAY"

class TransactionType(str, Enum):
    CREATE_PARCEL = "CREATE_PARCEL"
    TRANSFER = "TRANSFER"
    SALE = "SALE"
    MORTGAGE_CREATE = "MORTGAGE_CREATE"
    MORTGAGE_RELEASE = "MORTGAGE_RELEASE"
    SUBDIVIDE = "SUBDIVIDE"
    MERGE = "MERGE"
    DISPUTE_RAISE = "DISPUTE_RAISE"
    DISPUTE_RESOLVE = "DISPUTE_RESOLVE"
    LAND_USE_CHANGE = "LAND_USE_CHANGE"

class TransactionStatus(str, Enum):
    INITIATED = "INITIATED"
    LOCKED = "LOCKED"
    VALIDATED = "VALIDATED"
    DEPARTMENT_APPROVAL_PENDING = "DEPARTMENT_APPROVAL_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMMITTED = "COMMITTED"

class DepartmentNode(str, Enum):
    REVENUE_DEPARTMENT = "REVENUE_DEPARTMENT"
    SUB_REGISTRAR = "SUB_REGISTRAR"
    SURVEY_DEPARTMENT = "SURVEY_DEPARTMENT"
    REVENUE_COURT = "REVENUE_COURT"
    MUNICIPAL_CORP = "MUNICIPAL_CORP"
    FINANCIAL_INSTITUTION = "FINANCIAL_INSTITUTION"
